nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000', 'https://pickenchicken.com', 'https://app.pickenchicken.com']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
