<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512184258 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prosopon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, bot_key VARCHAR(80) DEFAULT NULL, display_name VARCHAR(80) NOT NULL, is_permanent BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, arrived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E1C5964D218E ON prosopon (location_id)');
        $this->addSql('CREATE INDEX IDX_8A8E1C59A76ED395 ON prosopon (user_id)');
        $this->addSql('ALTER TABLE prosopon ADD CONSTRAINT FK_8A8E1C5964D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prosopon ADD CONSTRAINT FK_8A8E1C59A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prosopon DROP CONSTRAINT FK_8A8E1C5964D218E');
        $this->addSql('ALTER TABLE prosopon DROP CONSTRAINT FK_8A8E1C59A76ED395');
        $this->addSql('DROP TABLE prosopon');
    }
}
