<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512000217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: app_user, session, competition, game, picks, bot snapshots, player progress, app_config';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(50) DEFAULT NULL, roles JSON NOT NULL, login_token VARCHAR(64) DEFAULT NULL, login_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username)');
        $this->addSql('CREATE TABLE bot_pick_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bot_id VARCHAR(50) NOT NULL, pick VARCHAR(10) NOT NULL, signal_strength NUMERIC(5, 2) DEFAULT NULL, metadata JSON NOT NULL, result VARCHAR(10) DEFAULT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F987D35E48FD905 ON bot_pick_snapshot (game_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F987D35E48FD90592C1C487 ON bot_pick_snapshot (game_id, bot_id)');
        $this->addSql('CREATE TABLE competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, sport_key VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, defeat_condition_type VARCHAR(20) NOT NULL, defeat_condition_config JSON NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE competition_segment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(20) DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, competition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_73435CB7B39D312 ON competition_segment (competition_id)');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, odds_api_event_id VARCHAR(50) DEFAULT NULL, home_team VARCHAR(100) NOT NULL, away_team VARCHAR(100) NOT NULL, commence_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, spread NUMERIC(5, 1) DEFAULT NULL, home_score INT DEFAULT NULL, away_score INT DEFAULT NULL, ats_result VARCHAR(10) DEFAULT NULL, chicken_pick VARCHAR(10) DEFAULT NULL, chicken_bot_id VARCHAR(50) DEFAULT NULL, chicken_signal_strength NUMERIC(5, 2) DEFAULT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, segment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318CDB296AAD ON game (segment_id)');
        $this->addSql('CREATE TABLE player_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, current_bot_id VARCHAR(50) DEFAULT NULL, zone VARCHAR(20) NOT NULL, ladder_position INT NOT NULL, series_wins INT NOT NULL, series_losses INT NOT NULL, total_wins INT NOT NULL, total_losses INT NOT NULL, defeated_bots JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, competition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_24D6B3A6A76ED395 ON player_progress (user_id)');
        $this->addSql('CREATE INDEX IDX_24D6B3A67B39D312 ON player_progress (competition_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24D6B3A6A76ED3957B39D312 ON player_progress (user_id, competition_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D044D5D45F37A13B ON session (token)');
        $this->addSql('CREATE INDEX IDX_D044D5D4A76ED395 ON session (user_id)');
        $this->addSql('CREATE TABLE user_pick (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pick VARCHAR(10) NOT NULL, result VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E34C4352A76ED395 ON user_pick (user_id)');
        $this->addSql('CREATE INDEX IDX_E34C4352E48FD905 ON user_pick (game_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E34C4352A76ED395E48FD905 ON user_pick (user_id, game_id)');
        $this->addSql('ALTER TABLE bot_pick_snapshot ADD CONSTRAINT FK_2F987D35E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_segment ADD CONSTRAINT FK_73435CB7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318CDB296AAD FOREIGN KEY (segment_id) REFERENCES competition_segment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player_progress ADD CONSTRAINT FK_24D6B3A6A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player_progress ADD CONSTRAINT FK_24D6B3A67B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_pick ADD CONSTRAINT FK_E34C4352A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_pick ADD CONSTRAINT FK_E34C4352E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('CREATE TABLE app_config (key VARCHAR(100) NOT NULL, value TEXT NOT NULL, PRIMARY KEY (key))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bot_pick_snapshot DROP CONSTRAINT FK_2F987D35E48FD905');
        $this->addSql('ALTER TABLE competition_segment DROP CONSTRAINT FK_73435CB7B39D312');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318CDB296AAD');
        $this->addSql('ALTER TABLE player_progress DROP CONSTRAINT FK_24D6B3A6A76ED395');
        $this->addSql('ALTER TABLE player_progress DROP CONSTRAINT FK_24D6B3A67B39D312');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4A76ED395');
        $this->addSql('ALTER TABLE user_pick DROP CONSTRAINT FK_E34C4352A76ED395');
        $this->addSql('ALTER TABLE user_pick DROP CONSTRAINT FK_E34C4352E48FD905');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE bot_pick_snapshot');
        $this->addSql('DROP TABLE competition');
        $this->addSql('DROP TABLE competition_segment');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE player_progress');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE user_pick');
        $this->addSql('DROP TABLE app_config');
    }
}
