<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260811162739 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Bankroll and Bet entities (Daybook journal spine), and price columns on Game.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bankroll (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_fae BOOLEAN NOT NULL, starting_balance INT NOT NULL, current_balance INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C0FA5AA76ED395 ON bankroll (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9C0FA5AA76ED395BE410279 ON bankroll (user_id, is_fae)');
        $this->addSql('CREATE TABLE bet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stake INT NOT NULL, price_taken INT DEFAULT NULL, result VARCHAR(10) DEFAULT NULL, payout INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, settled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, pick_id INT NOT NULL, bankroll_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBF0EC9BA76ED395 ON bet (user_id)');
        $this->addSql('CREATE INDEX IDX_FBF0EC9B725DA5D8 ON bet (bankroll_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FBF0EC9BF54A307A ON bet (pick_id)');
        $this->addSql('ALTER TABLE bankroll ADD CONSTRAINT FK_9C0FA5AA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9BA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9BF54A307A FOREIGN KEY (pick_id) REFERENCES user_pick (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9B725DA5D8 FOREIGN KEY (bankroll_id) REFERENCES bankroll (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD home_price INT DEFAULT NULL');
        $this->addSql('ALTER TABLE game ADD away_price INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bankroll DROP CONSTRAINT FK_9C0FA5AA76ED395');
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9BA76ED395');
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9BF54A307A');
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9B725DA5D8');
        $this->addSql('DROP TABLE bankroll');
        $this->addSql('DROP TABLE bet');
        $this->addSql('ALTER TABLE game DROP home_price');
        $this->addSql('ALTER TABLE game DROP away_price');
    }
}
