<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812150119 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_settings and bot_subscription tables';
    }

    public function up(Schema $schema): void
    {
        // Note: app_config is a real, actively-used table (raw SQL in SimulatedClockService,
        // no Doctrine entity) — the auto-generated diff mistook it for an orphan and wanted
        // to drop it. That line has been removed; do not add it back.
        $this->addSql('CREATE TABLE bot_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bot_id VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_41C61969A76ED395 ON bot_subscription (user_id)');
        $this->addSql('CREATE TABLE user_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, avatar_url VARCHAR(255) DEFAULT NULL, personal_statement TEXT DEFAULT NULL, pick_style VARCHAR(30) DEFAULT NULL, account_type VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C844C5A76ED395 ON user_settings (user_id)');
        $this->addSql('ALTER TABLE bot_subscription ADD CONSTRAINT FK_41C61969A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE bot_subscription DROP CONSTRAINT FK_41C61969A76ED395');
        $this->addSql('ALTER TABLE user_settings DROP CONSTRAINT FK_5C844C5A76ED395');
        $this->addSql('DROP TABLE bot_subscription');
        $this->addSql('DROP TABLE user_settings');
    }
}
